# Configuration for r10k. For example:
#
forge "https://forgeapi.puppetlabs.com"

mod "puppetlabs/stdlib"
mod "puppetlabs/apt"
mod "puppetlabs/mysql"
mod "puppetlabs/apache"
mod "example42/php",
  :git => "https://github.com/example42/puppet-php"
